### ISSUE TITLE
Submodule in parent please

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-multisite#4]
@gauravchaudhari02 , can you please add a submodule in the parent to this repo?

**Comment by gauravchaudhari02** [comment]
@johnbent, Do you mean `cortx` repository by parent repo?

**Comment by johnbent** [comment]
Yes.  Thanks.

**Comment by kaustubh-d** [comment]
@gauravchaudhari02 Looks like this is done? If yes please close. cc @priyankdal

**Comment by mukul-seagate11** [comment]
submodule has been created for multisite repo in cortx parent as per https://github.com/Seagate/cortx-multisite/tree/50800f8b946a4627a8351303a8cf0d8c83a9ef09 so closing the issue
